CREATE TABLE meetups (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, start DATETIME NOT NULL, location VARCHAR(150) NOT NULL, Description VARCHAR(1000) NOT NULL);
CREATE TABLE statuses (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, Value VARCHAR(50) NOT NULL);
CREATE TABLE users (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(150) NOT NULL, Birthdate DATETIME NOT NULL, Introduction VARCHAR(500), Avatar VARCHAR(1000), Email VARCHAR(150));
CREATE TABLE meetupregistrations (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, StatusId INT NOT NULL, MeetupId INT NOT NULL, UserId INT NOT NULL);